---
- name: Build and install conserver
  ansible.builtin.raw: |
    if [ ! -f {{ path_conserver_bin }} ]; then
      rm -rf {{ path_conserver_src }}
      git clone {{ repo_conserver }} {{ path_conserver_src }}
      cd {{ path_conserver_src }} && make init && make conf && make build && make install
      rm -rf {{ path_conserver_src }}
    fi
  changed_when: false
