#!/usr/bin/env python3
"""Generate the load-test IOC databases and registration lists.

Step 1 adds 400 scalars at 1 Hz; step 2 adds 300 scalars at 1 Hz, 100 at
10 Hz under the VeryFast policy, and three 1000-element waveforms. Writes
load1.db, load2.db, pvs-load1.csv, pvs-load2.csv and pvs-all.csv (the day-1
list plus both steps, read by the sampler). Stops on a store-key collision.
"""

import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from gen_soak import counter, store_key, wave  # noqa: E402

# (step, group, count, name pattern, scan, kind, method, period, policy)
LOAD = [
    (1, "load1", 400, "AASOAK:L1:CH{n:03d}", "1 second", "counter", "MONITOR", "1.0", ""),
    (2, "load2", 300, "AASOAK:L2:CH{n:03d}", "1 second", "counter", "MONITOR", "1.0", ""),
    (2, "load2fast", 100, "AASOAK:L2F:CH{n:03d}", ".1 second", "counter", "MONITOR", "0.1", "VeryFast"),
    (2, "load2wave", 3, "AASOAK:L2WF:CH{n:02d}", "1 second", "wave", "MONITOR", "1.0", ""),
]
HEADER = ["pv", "group", "scan", "method", "period", "policy", "store_key"]


def main():
    with open(os.path.join(HERE, "pvs.csv"), newline="") as f:
        day1 = [list(r.values()) for r in csv.DictReader(f)]
    steps = {1: ([], []), 2: ([], [])}
    for step, group, count, pattern, scan, kind, method, period, policy in LOAD:
        db, rows = steps[step]
        for n in range(1, count + 1):
            name = pattern.format(n=n)
            db.append(counter(name, scan, n) if kind == "counter" else wave(name, scan))
            rows.append([name, group, scan, method, period, policy, store_key(name)])

    allrows = day1 + steps[1][1] + steps[2][1]
    keys = [r[6] for r in allrows]
    dupes = sorted({k for k in keys if keys.count(k) > 1})
    if dupes:
        sys.exit(f"store key collision: {dupes}")

    for step, (db, rows) in steps.items():
        with open(os.path.join(HERE, f"load{step}.db"), "w") as f:
            f.write("# Generated by gen_load.py; do not edit.\n")
            f.write("\n".join(db))
        with open(os.path.join(HERE, f"pvs-load{step}.csv"), "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(HEADER)
            w.writerows(rows)
    with open(os.path.join(HERE, "pvs-all.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(HEADER)
        w.writerows(allrows)
    print(f"step1 {len(steps[1][1])} PVs, step2 {len(steps[2][1])} PVs, all {len(allrows)}")


if __name__ == "__main__":
    main()
