---
# roles/app_con/tasks/main.yml
- name: Build and install con
  ansible.builtin.raw: |
    if [ ! -f {{ path_con_bin }} ]; then
      rm -rf {{ path_con_src }}
      git clone {{ repo_con }} {{ path_con_src }}
      cd {{ path_con_src }} && make && make install DESTDIR=/usr/local
      rm -rf {{ path_con_src }}
    fi
  changed_when: false
