---
# playbooks/species/iocrunner.yml
# iocrunner = P_testusers P_iocrunner (P_con P_conserver P_procserv)
#             P_epics P_provenance |bare>
- import_playbook: ../operators/common.yml
- import_playbook: ../operators/provenance.yml
- import_playbook: ../operators/epics.yml
- import_playbook: ../operators/con.yml
- import_playbook: ../operators/conserver.yml
- import_playbook: ../operators/procserv.yml
- import_playbook: ../operators/iocrunner.yml
- import_playbook: ../operators/testusers.yml
