---
# inventory/group_vars/rocky8.yml
epics_os_dir: "rocky-8.10"

# Rocky 8 ships python3.9 as an add-on module; make it the default python
# for the epics_build role.
pkg_python_redhat:
  - python39
  - python39-pip
runtime_python_alt_path: "/usr/bin/python3.9"
pip_bin:                 "/usr/bin/pip3.9"
